import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AuthModule } from '../auth/auth.module';
import { KhoaController } from './quan-ly-khoa/quan-ly-khoa.controller';
import { ClbController } from './clb/clb.controller';
import { QtvController } from './qtv/qtv.controller';
import { KhoaService } from './shared/khoa.service';
import {
  NamHoc,
  HocKy,
  KhoaHoc,
  VaiTro,
  Quyen,
  VaiTro_Quyen,
  TaiKhoan,
  SinhVien,
  GiangVien,
  NhaMay,
  ThongBao,
  ThongBaoFile,
  DotKienTap,
  LichKienTap,
  DotKienTap_SinhVien,
  ChuyenThamQuan,
  PhanCongGiangVienDanDoan,
  PhieuDangKy,
  YeuCauHuyDangKy,
  DanhSachDen,
  HoaDonLePhi,
  DonHoanPhi,
  PhanCongGVHD,
  DiemDanh,
  BaiThuHoach,
  DiemPhieuThamQuan,
  PhieuThamQuan,
  PhieuDeXuatChuyenThamQuan,
  HoiDongChamBaoCao,
  HoiDong_ThanhVien,
  DiemHoiDong_ChiTiet,
  BoChuyenBaoCao,
  TaiKhoanThuHuong,
} from '../entities/qlkt.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      NamHoc,
      HocKy,
      KhoaHoc,
      VaiTro,
      Quyen,
      VaiTro_Quyen,
      TaiKhoan,
      SinhVien,
      GiangVien,
      NhaMay,
      ThongBao,
      ThongBaoFile,
      DotKienTap,
      LichKienTap,
      DotKienTap_SinhVien,
      ChuyenThamQuan,
      PhanCongGiangVienDanDoan,
      PhieuDangKy,
      YeuCauHuyDangKy,
      DanhSachDen,
      HoaDonLePhi,
      DonHoanPhi,
      PhanCongGVHD,
      DiemDanh,
      BaiThuHoach,
      DiemPhieuThamQuan,
      PhieuThamQuan,
      PhieuDeXuatChuyenThamQuan,
      HoiDongChamBaoCao,
      HoiDong_ThanhVien,
      DiemHoiDong_ChiTiet,
      BoChuyenBaoCao,
      TaiKhoanThuHuong,
    ]),
    AuthModule,
  ],
  controllers: [KhoaController, ClbController, QtvController],
  providers: [KhoaService],
  exports: [KhoaService],
})
export class KhoaModule {}
