import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AuthModule } from '../auth/auth.module';
import { KhoaController } from './khoa.controller';
import { ClbController } from './clb.controller';
import { KhoaService } from './khoa.service';
import {
  NamHoc,
  HocKy,
  Khoa,
  TaiKhoan,
  SinhVien,
  GiangVien,
  NhaMay,
  ThongBao,
  ThongBaoFile,
  DotKienTap,
  LichKienTap,
  LichKienTap_SinhVien,
  ChuyenThamQuan,
  ChuyenThamQuan_GiangVienDanDoan,
  PhieuDangKy,
  YeuCauHuyDangKy,
  DanhSachDen,
  HoaDonLePhi,
  DonHoanPhi,
  PhanCongGVHD,
  DiemDanh,
  BaiThuHoach,
  DiemPhieuThamQuan,
  DiemChuanBi,
  DiemBaiThuHoach,
  PhieuThamQuan,
  DeXuatChuyenThamQuan,
  HoiDongChamBaoCao,
  HoiDong_ThanhVien,
  DiemHoiDong_ChiTiet,
  BoChuyenBaoCao,
  BoChuyenBaoCao_Chuyen,
} from '../entities/qlkt.entity';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      NamHoc,
      HocKy,
      Khoa,
      TaiKhoan,
      SinhVien,
      GiangVien,
      NhaMay,
      ThongBao,
      ThongBaoFile,
      DotKienTap,
      LichKienTap,
      LichKienTap_SinhVien,
      ChuyenThamQuan,
      ChuyenThamQuan_GiangVienDanDoan,
      PhieuDangKy,
      YeuCauHuyDangKy,
      DanhSachDen,
      HoaDonLePhi,
      DonHoanPhi,
      PhanCongGVHD,
      DiemDanh,
      BaiThuHoach,
      DiemPhieuThamQuan,
      DiemChuanBi,
      DiemBaiThuHoach,
      PhieuThamQuan,
      DeXuatChuyenThamQuan,
      HoiDongChamBaoCao,
      HoiDong_ThanhVien,
      DiemHoiDong_ChiTiet,
      BoChuyenBaoCao,
      BoChuyenBaoCao_Chuyen,
    ]),
    AuthModule,
  ],
  controllers: [KhoaController, ClbController],
  providers: [KhoaService],
  exports: [KhoaService],
})
export class KhoaModule {}
